name: Build ESP32 Smart Gyro BIN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Install ESP32 Platform
        run: |
          arduino-cli core update-index --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core install esp32:esp32@3.0.7 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

      - name: Compile Sketch
        run: |
          # FQBN cấu hình cho ESP32 Dev Module với Flash Mode là DIO
          arduino-cli compile --fqbn esp32:esp32:esp32 \
          --build-property "build.flash_mode=dio" \
          --build-property "build.flash_freq=40m" \
          --output-dir ./build ./esp32_fc/esp32_fc.ino

      - name: Upload BIN Artifact
        uses: actions/upload-artifact@v3
        with:
          name: esp32-smart-gyro-bin
          path: ./build/*.bin
          
